export enum ActionTypes {
  SET_IS_LOADING = "[DARIO_HERRERA_POKEDEX] SET_IS_LOADING",
  SET_POKEMON_LIST_RESPONSE = "[DARIO_HERRERA_POKEDEX] SET_POKEMON_LIST_RESPONSE",
  SET_POKEMON_DETAILS_RESPONSE = "[DARIO_HERRERA_POKEDEX] SET_POKEMON_DETAILS_RESPONSE",
  SET_IS_NOT_FOUND = "[DARIO_HERRERA_POKEDEX] SET_IS_NOT_FOUND",
}
